export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_OTP: '/signup/otp',
  SIGNUP_PROFILE: '/signup/profile',
  SIGNUP_MART_EMAIL_OTP: '/signup/mart-email-otp',
  SIGNUP_OWNER: '/signup/owner',
  SIGNUP_LOCATION: '/signup/location',
  PORTAL_REGISTRATION: '/portal/complete-registration',
  DASHBOARD: '/dashboard',
  ORDERS: '/orders',
  ORDER_DETAILS: '/orders/:orderId',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAILS: '/customers/:customerId',
  DELIVERY_STAFF: '/delivery-staff',
  SERVICES: '/services',
  PROMOTIONS: '/promotions',
  PAYMENTS: '/payments',
  ANALYTICS: '/analytics',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
};
